language: python

# This doesn't matter much as tox will select the version to execute
# tests against
python: 3.4

# dev.txt only contains the dependencies required to run tox, tox will
# install the rest.
install: "pip install -r requirements/dev.txt"

# Create a matrix containing each tox environment
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=pypy
    - "TOX_ENV=py27-pep8,py34-pep8"
    - TOX_ENV=docs
    - TOX_ENV=readme

script: tox -e $TOX_ENV
